---
- name: Create fluent bit directory
  become: true
  file:
    path: "{{ fluent_bit_install_path }}"
    state: directory

- name: Install fluent bit docker-compose
  become: true
  template:
    src: docker-compose.yml
    dest: "{{ fluent_bit_install_path }}/"
    mode: '0644'

- name: Create fluent bit configuration directory
  become: true
  file:
    path: "{{ fluent_bit_install_path }}/cfg"
    state: directory

- name: Install fluent bit configuration files
  become: true
  template:
    src: "{{ item }}.conf"
    dest: "{{ fluent_bit_install_path }}/cfg/"
    mode: '0644'
  with_items:
    - fluent-bit
    - traefik-filters
    - nextcloud-filters
    - matomo-filters
    - outputs
    - parsers
