---
- name: App list
  ansible.builtin.shell:
    chdir: "{{ nextcloud_install_path }}"
    cmd: "{{ nextcloud_occ_bin }} --output=json app:list"
  register: nc_apps_output
  check_mode: no
  changed_when: no

- set_fact:
    nc_apps_dict: "{{ nc_apps_output.stdout | from_json }}"

- set_fact:
    nc_apps_enabled: "{{ nc_apps_dict.enabled.keys() | list }}"
    nc_apps_disabled: "{{ nc_apps_dict.disabled.keys() | list }}"

- name: Install apps
  with_items: "{{ nextcloud_install_apps | difference(nc_apps_enabled + nc_apps_disabled) }}"
  ansible.builtin.shell:
    executable: /bin/bash
    chdir: "{{ nextcloud_install_path }}"
    cmd: "{{ nextcloud_occ_bin }} app:install {{ item }}"

- name: Enable apps
  with_items: "{{ (nextcloud_enable_apps + nextcloud_install_apps) | difference(nc_apps_enabled) }}"
  ansible.builtin.shell:
    chdir: "{{ nextcloud_install_path }}"
    cmd: "{{ nextcloud_occ_bin }} app:enable {{ item }}"

- name: Disable apps
  with_items: "{{ nextcloud_disable_apps | difference(nc_apps_disabled) }}"
  ansible.builtin.shell:
    chdir: "{{ nextcloud_install_path }}"
    cmd: "{{ nextcloud_occ_bin }} app:disable {{ item }}"