---
- name: Create Nextcloud directory {{ nextcloud_install_path }}
  become: yes
  file:
    path: "{{ nextcloud_install_path }}"
    state: directory
  register: nextcloud_create_directory

- name: Create Nextcloud config directory in {{ nextcloud_install_path }}
  become: yes
  file:
    path: "{{ nextcloud_install_path }}/cfg"
    state: directory

- name: Create Nextcloud data directory in {{ nextcloud_install_path }}
  become: yes
  file:
    path: "{{ nextcloud_install_path }}/data"
    state: directory

- name: Install Nextcloud docker-compose in {{ nextcloud_install_path }}
  become: yes
  template:
    src: "docker-compose.yml"
    dest: "{{ nextcloud_install_path }}/"
    mode: '0644'
    backup: yes
  register: nextcloud_docker_compose
  notify: restart nextcloud

- name: Run Nextcloud database
  when: nextcloud_docker_compose.changed and nextcloud_postgres_embedded
  become: yes
  docker_compose:
    project_src: "{{ nextcloud_install_path }}"
    services: [ 'nextcloud-db', 'nextcloud-redis' ]

- name: Wait for Nextcloud DB is healthy
  when: nextcloud_docker_compose.changed and nextcloud_postgres_embedded
  become: yes
  shell:
    chdir: "{{ nextcloud_install_path }}"
    cmd: docker-compose ps nextcloud-db | grep "(healthy)"
  register: cmd_res
  retries: 20
  delay: 15
  until: cmd_res.rc == 0

- name: Pause for 20 seconds before run Nextcloud
  when: nextcloud_docker_compose.changed and nextcloud_postgres_embedded
  pause:
    seconds: 20

- name: Flush handlers
  meta: flush_handlers

- name: Configure
  ansible.builtin.include_tasks: configure.yml
  args:
    apply:
      tags: [ 'nextcloud/configure' ]
  tags: [ 'always' ]