---
- name: Create Traefik install directory in {{ traefik_install_path }}
  become: yes
  file:
    path: "{{ traefik_install_path }}"
    state: directory

- name: Install python lib passlib
  pip:
    name: passlib

- name: Generate passwd file for traefik in {{ traefik_install_path }}
  become: yes
  htpasswd:
    path: "{{ traefik_install_path }}/.htpasswd"
    name: "{{ traefik_ui_username }}"
    password: "{{ traefik_ui_password }}"
    mode: 0640
  register: traefik_config

- name: Install Traefik docker-compose in {{ traefik_install_path }}
  become: yes
  template:
    src: "docker-compose.yml"
    dest: "{{ traefik_install_path }}/"
    mode: '0644'
    backup: yes
  register: traefik_docker_compose

- name: Restart traefik
  when: traefik_docker_compose.changed or traefik_config.changed | bool
  become: yes
  docker_compose:
    project_src: "{{ traefik_install_path }}"
    restarted: yes
