---
name: Test playbook

on:
  pull_request:



jobs:
  test:
    runs-on: ubuntu-20.04
    name: Test playbook

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install ansible requests docker docker-compose jmespath

      - name: Run test
        run: |
          ansible-playbook -i tests/hosts tests/test.yml --limit github_action
